# Setup in CircleCI account the following ENV variables:
# PACKAGECLOUD_TOKEN
version: 2
jobs:
  build:
    machine: true
    environment:
      DEB: trusty xenial bionic
      RPM: el6 el7
      IS_ENTERPRISE: 1
      DEPLOY_PACKAGES: 1
    steps:
      - checkout
      - run:
          name: Download helper scripts (for packagecloud)
          command: |
            mkdir ~/scripts
            wget -qO - https://github.com/StackStorm/st2-packages/raw/master/.circle/packagecloud.sh > ~/scripts/packagecloud.sh
            chmod 755 ~/scripts/packagecloud.sh
            echo "export PATH=${HOME}/scripts:${PATH}" >> $BASH_ENV
      - run:
          name: Switch to supported version of Node
          command: |
            set +e
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            nvm install 4
            nvm alias default 4

            # Each step uses the same `$BASH_ENV`, so need to modify it
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
      - run:
          name: Export package version
          command: |
            PKG_VERSION=$(node -e "console.log(require('./package.json').st2_version);")
            PKG_RELEASE=$(packagecloud.sh next-revision trusty ${PKG_VERSION} st2flow)
            echo "export PKG_VERSION=${PKG_VERSION}" >> $BASH_ENV
            echo "export PKG_RELEASE=${PKG_RELEASE}" >> $BASH_ENV
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install rpm jq devscripts debhelper
            gem install package_cloud -v 0.2.45
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run unit tests
          command: npm run test
      - run:
          name: Create directories for Artifacts
          command: mkdir ~/artifacts && cd ~/artifacts && mkdir ${DEB} ${RPM} logs
      - run:
          name: Make deb packages
          command: |
            make deb
            echo $DEB | tr ' ' '\n' | xargs -I{} cp -vr ../st2flow_*.{deb,changes} ~/artifacts/{}
      - run:
          name: Make RPM packages
          command: |
            make rpm
            echo $RPM | tr ' ' '\n' | xargs -I{} cp -vr ../st2flow-*.rpm ~/artifacts/{}
      - store_artifacts:
          path: ~/artifacts
          destination: packages
      - persist_to_workspace:
          root: /home/circleci/artifacts
          paths:
            - trusty
            - xenial
            - bionic
            - el6
            - el7
  deploy:
    docker:
      - image: ruby:2.4.4
    environment:
      ARTIFACTS: /home/circleci/artifacts
      DISTROS: trusty xenial bionic el6 el7
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/artifacts
      - run:
          name: List workspace files
          command: find $ARTIFACTS | sed 's|[^/]*/|  |g'
      - run:
          name: Install dependencies
          command: |
            set -x
            apt-get -qq update
            apt-get -y install jq
            wget -qO - https://github.com/StackStorm/st2-packages/raw/master/.circle/packagecloud.sh > ~/packagecloud.sh
            chmod 755 ~/packagecloud.sh
            gem install package_cloud
      - run:
          name: Deploy to packagecloud
          command: |
            for distro in ${DISTROS}; do
              ~/packagecloud.sh deploy $distro $ARTIFACTS/$distro
            done
workflows:
  version: 2
  build-deploy-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - /v[0-9]+\.[0-9]+/
                - feature/circleci
